files:
  include: "**/*.scss"
options:
  formatter: stylish 
  merge-default-rules: false
rules:
  # bem-depth: 1  working
  border-zero: 0
  brace-style: 1
  class-name-format: 0
  clean-import-paths:
    - 0
    - filename-extension: true
      leading-underscore: true
  declarations-before-nesting: 1
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 0
  hex-length: 0
  hex-notation: 1
  id-name-format: 0
  indentation:
    - 1
    # - size: "tab" done
  leading-zero:
    - 1
    - include: true
  mixin-name-format: 0
  mixins-before-declarations:
    - 1
    - exclude: ['respond-to']
  nesting-depth: 0
  no-color-keywords: 0
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 0
  no-trailing-zero: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  placeholder-in-extend: 1
  placeholder-name-format: 0
  property-sort-order:
    - 1
    - ignore-custom-properties: false
      order: "alphabetical"
  property-units: 1
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang: 1
  space-after-colon: 1
  space-after-comma: 1
  space-before-bang: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 0
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property: 0
  variable-name-format: 0
  zero-unit: 0
